# Generated by Django 4.0.5 on 2022-06-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_task_complete_task_date_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date_complete',
            new_name='date_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='Insert Description'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Insert Title', max_length=120),
        ),
    ]
