# Generated by Django 4.0.5 on 2022-06-24 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_complete_task_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='completion date'),
        ),
    ]
