# Generated by Django 4.0.5 on 2022-06-15 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='date_complete',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='creation date'),
        ),
    ]
